### PR TITLE
refactor context to fix OpenNeuro terms and add TermsCollection shape

### PR DESCRIPTION
**Pull request by sanuann**

### CODE REVIEW

**Comment by sanuann** [comment]
@nqueder Note: all of the `participants.jsonld` files will need to be refactored to have an `@type: nidm:TermsCollection` for the validator to work.

**Comment by dbkeator** [comment]
Hi,
Should I merge this even though some tests are failing?

Thx

**Comment by sanuann** [comment]
> Hi,
> Should I merge this even though some tests are failing?
> 
> Thx

yes please.

**Comment by nqueder** [comment]
@dbkeator yes, thanks! the only test that passes right now is "Generate Single JSONLD File"

**Pull request merged**
